apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app3
spec:
  selector:
    matchLabels:
      app: web-app3
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web-app3
    spec:
      containers:
      - name: web2
        image: rajatkokane/projectfinal
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-app3
  labels:
    run: web-app3
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    protocol: TCP
  selector:
    run: web-app3
